//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionMiHogarAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaClinica
    {
        public int id { get; set; }
        public int idPaciente { get; set; }
        public int idTipoIngreso { get; set; }
        public System.DateTime fecha { get; set; }
        public bool aseoBucal { get; set; }
        public bool aseoGenital { get; set; }
        public bool aseoCavidades { get; set; }
        public string hidratacion { get; set; }
        public bool bano { get; set; }
        public string desposiciones { get; set; }
        public decimal tempAxilar { get; set; }
        public string frecuenciaResp { get; set; }
        public bool cuidadoUnaPelo { get; set; }
        public bool daoc { get; set; }
        public string pulso { get; set; }
        public string presionArterial { get; set; }
        public decimal saturacion { get; set; }
        public string diuresis { get; set; }
        public bool vomitos { get; set; }
        public string otros { get; set; }
        public string observaciones { get; set; }
        public int idTrabajador { get; set; }
        public bool eliminado { get; set; }
        public Nullable<System.DateTime> fechaEliminado { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual TipoIngreso TipoIngreso { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
