//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionMiHogarAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MihogarAPPEntities : DbContext
    {
        public MihogarAPPEntities()
            : base("name=MihogarAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Certificados> Certificados { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<FichaClinica> FichaClinica { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<ImagenesPacientes> ImagenesPacientes { get; set; }
        public virtual DbSet<ImagenesTrabajador> ImagenesTrabajador { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Postulaciones> Postulaciones { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<TipoIngreso> TipoIngreso { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Tutor> Tutor { get; set; }
        public virtual DbSet<Visitas> Visitas { get; set; }
        public virtual DbSet<HorarioTrabajador> HorarioTrabajador { get; set; }
    }
}
